nginx:
    build: ./nginx
    ports:
        - 80:80
    links:
        - mysql
    volumes:
        - ./app:/var/www/html

mysql:
    image: mysql:latest
    ports:
        - 3306:3306
    volumes:
        - ./data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: password

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
